Document: suricata
Title: Debian suricata Manual
Author: <insert document author here>
Abstract: This manual describes what suricata is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/suricata/suricata.sgml.gz

Format: postscript
Files: /usr/share/doc/suricata/suricata.ps.gz

Format: text
Files: /usr/share/doc/suricata/suricata.text.gz

Format: HTML
Index: /usr/share/doc/suricata/html/index.html
Files: /usr/share/doc/suricata/html/*.html
